import 'package:flutter/material.dart';

class Const {
  List<Map> data = [
    {
      "name": "Shai Hope",
      "point": "10.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "R Pant",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "Nichoals Pooran",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
  ];
  List<dynamic> bat = [
    {
      "name": "L Rahul",
      "point": "10.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "S Brooks",
      "point": "9.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "S Dhawan",
      "point": "9.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "R Sharma",
      "point": "9.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "S Lyer",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "R Gaikwad",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "S Yadav",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "M Agarwal",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "D beavo",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "D Hooda",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "B King",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "N Bonner",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
  ];

  List<dynamic> bowl = [
    {
      "name": "SN Thakur",
      "point": "10.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "P Krishna",
      "point": "9.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "R Bishnoi",
      "point": "9.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "D Chahar",
      "point": "9.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "Y Chahal",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "H Walsh",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "A Hosein",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "R Shepherd",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "A joseph",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "M Siaj",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "Avesh Khan",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "K Yadav",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
  ];
  List<dynamic> ar = [
    {
      "name": "O Smith",
      "point": "9.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "W Sunder",
      "point": "9.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "F aLLEN",
      "point": "8.5",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "J Holder",
      "point": "8.",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
    {
      "name": "K Pollard",
      "point": "8.0",
      "icon": Icons.add,
      "icons": Icons.minimize,
      "color": Colors.red,
      "colors": Colors.green,
      "isselected": false,
    },
  ];
}
